from ScoutSuite.providers.aws.facade.base import AWSFacade
from ScoutSuite.providers.aws.resources.base import AWSResources


class Domains(AWSResources):
    """The SageMaker Studio domains of a region. A domain is the tenancy boundary of Studio: it fixes
    the VPC the user applications run in, the EFS file system every user profile gets a home
    directory on, how users authenticate, and the execution role their notebooks assume by default."""

    def __init__(self, facade: AWSFacade, region: str):
        super().__init__(facade)
        self.region = region

    async def fetch_all(self):
        for raw_domain in await self.facade.sagemaker.get_domains(self.region):
            id, domain = self._parse_domain(raw_domain)
            self[id] = domain

    def _parse_domain(self, raw_domain):
        created = raw_domain.get('CreationTime')

        domain = {}
        # The domain id is generated by SageMaker and is what every other API call takes
        domain['id'] = raw_domain['DomainId']
        domain['name'] = raw_domain.get('DomainName')
        domain['arn'] = raw_domain.get('DomainArn')
        domain['region'] = self.region
        domain['status'] = raw_domain.get('Status')
        domain['failure_reason'] = raw_domain.get('FailureReason')
        domain['creation_time'] = created.strftime('%Y-%m-%d %H:%M:%S') if created else None
        domain['url'] = raw_domain.get('Url')
        # SSO federates Studio access to the identity source of IAM Identity Center; IAM means every
        # user reaches Studio by assuming a role and calling CreatePresignedDomainUrl
        domain['auth_mode'] = raw_domain.get('AuthMode')

        self._parse_network(raw_domain, domain)
        self._parse_encryption(raw_domain, domain)
        self._parse_default_user_settings(raw_domain, domain)
        self._parse_domain_settings(raw_domain, domain)
        self._parse_user_profiles(raw_domain, domain)

        return domain['id'], domain

    @staticmethod
    def _parse_network(raw_domain, domain):
        """Where the user applications of the domain are attached, and whether they may leave.

        PublicInternetOnly - the default - gives every notebook, terminal and kernel of the domain a
        network interface in a VPC SageMaker owns, with a route to the internet that no route table,
        security group or network ACL of the account governs and no VPC flow log records. VpcOnly
        puts those interfaces in the subnets of the domain instead, where reaching SageMaker itself
        needs VPC endpoints, and where what the domain may reach is decided by the account."""

        app_network_access_type = raw_domain.get('AppNetworkAccessType')

        domain['app_network_access_type'] = app_network_access_type
        # PublicInternetOnly is what SageMaker applies when the creation request says nothing
        domain['vpc_only_access'] = app_network_access_type == 'VpcOnly'
        domain['vpc_id'] = raw_domain.get('VpcId')
        domain['subnets'] = raw_domain.get('SubnetIds') or []
        # Service means SageMaker creates and attaches the security groups of the user applications
        # itself, so the ones declared on the domain are not the whole boundary
        domain['app_security_group_management'] = raw_domain.get('AppSecurityGroupManagement')
        # The security group SageMaker uses to allow the RStudio and Studio traffic that has to cross
        # between the domain VPC and the one SageMaker owns
        domain['domain_boundary_security_group'] = raw_domain.get('SecurityGroupIdForDomainBoundary')

    @staticmethod
    def _parse_encryption(raw_domain, domain):
        """The EFS file system holding the home directory of every user profile is always encrypted,
        so what is worth reporting is whose key protects it. Without a key of the account's choosing
        SageMaker uses one AWS manages, whose policy the account cannot change and whose use it
        cannot deny, which is the difference between being able to revoke access to years of
        notebooks, datasets and credentials left in them and not being able to."""

        # KmsKeyId is the key given at creation; HomeEfsFileSystemKmsKeyId is the deprecated name the
        # API still answers with for domains created before it was renamed
        kms_key_id = raw_domain.get('KmsKeyId') or raw_domain.get('HomeEfsFileSystemKmsKeyId')

        domain['kms_key_id'] = kms_key_id
        domain['encryption_with_cmk'] = bool(kms_key_id)
        domain['home_efs_file_system_id'] = raw_domain.get('HomeEfsFileSystemId')

    @staticmethod
    def _parse_default_user_settings(raw_domain, domain):
        """What a user profile gets unless it overrides it."""

        settings = raw_domain.get('DefaultUserSettings') or {}
        sharing = settings.get('SharingSettings') or {}

        domain['default_execution_role'] = settings.get('ExecutionRole')
        domain['default_security_groups'] = settings.get('SecurityGroups') or []
        # Allowed lets a user publish a notebook, with its cell output, to an S3 location as a URL
        # anybody holding it can open, which is a documented way for data pulled into a notebook to
        # leave the account without any bucket being made public
        domain['notebook_output_sharing'] = sharing.get('NotebookOutputOption')
        domain['notebook_output_sharing_enabled'] = sharing.get('NotebookOutputOption') == 'Allowed'
        domain['notebook_sharing_s3_path'] = sharing.get('S3OutputPath')
        domain['notebook_sharing_kms_key_id'] = sharing.get('S3KmsKeyId')
        # Disabled removes the Studio web portal from the profiles of the domain, leaving only the
        # applications reached through the SDK
        domain['studio_web_portal'] = settings.get('StudioWebPortal')

    @staticmethod
    def _parse_domain_settings(raw_domain, domain):
        settings = raw_domain.get('DomainSettings') or {}
        docker = settings.get('DockerSettings') or {}

        domain['domain_security_groups'] = settings.get('SecurityGroupIds') or []
        # USER_PROFILE_NAME makes SageMaker set the role session name of the execution role to the
        # user profile, so CloudTrail names the person behind each call the notebook makes; DISABLED,
        # the default, leaves every profile sharing one indistinguishable session identity
        domain['execution_role_identity_config'] = settings.get('ExecutionRoleIdentityConfig')
        domain['user_identity_propagated'] = settings.get('ExecutionRoleIdentityConfig') == 'USER_PROFILE_NAME'
        # ENABLED lets users build and run containers locally inside their Studio application
        domain['docker_access'] = docker.get('EnableDockerAccess')
        # The accounts a domain may pull images from when local Docker access is on
        domain['docker_vpc_only_trusted_accounts'] = docker.get('VpcOnlyTrustedAccounts') or []

    @staticmethod
    def _parse_user_profiles(raw_domain, domain):
        """The user profiles of the domain, each with the execution role its applications assume.

        A profile can override the domain default with a role of its own, which is how one person's
        notebooks end up with permissions the domain was never reviewed for, so the override is
        recorded rather than only the effective role."""

        default_execution_role = domain.get('default_execution_role')

        user_profiles = {}
        for raw_profile in raw_domain.get('user_profile_details') or []:
            name = raw_profile.get('UserProfileName')
            if not name:
                continue

            created = raw_profile.get('CreationTime')
            settings = raw_profile.get('UserSettings') or {}
            execution_role = settings.get('ExecutionRole')

            user_profiles[name] = {
                'id': name,
                'name': name,
                'arn': raw_profile.get('UserProfileArn'),
                'status': raw_profile.get('Status'),
                'creation_time': created.strftime('%Y-%m-%d %H:%M:%S') if created else None,
                # The identity the profile is federated to, set only on an SSO domain
                'sso_user_identifier': raw_profile.get('SingleSignOnUserIdentifier'),
                'sso_user_value': raw_profile.get('SingleSignOnUserValue'),
                'execution_role': execution_role or default_execution_role,
                'execution_role_overridden': bool(execution_role) and execution_role != default_execution_role,
                'security_groups': settings.get('SecurityGroups') or [],
            }

        domain['user_profiles'] = user_profiles
        domain['user_profiles_count'] = len(user_profiles)
