from xml.etree import ElementTree

from ScoutSuite.core.console import print_exception
from ScoutSuite.providers.aws.facade.base import AWSFacade
from ScoutSuite.providers.aws.resources.base import AWSResources
from ScoutSuite.providers.utils import get_non_provider_id

# The destination an ActiveMQ authorization entry applies to is named by whichever of these
# attributes is set, and the attribute itself says what kind of destination it is.
AUTHORIZATION_DESTINATION_TYPES = ('queue', 'topic', 'tempQueue', 'tempTopic')


class Brokers(AWSResources):
    def __init__(self, facade: AWSFacade, region: str):
        super().__init__(facade)
        self.region = region

    async def fetch_all(self):
        for raw_broker in await self.facade.mq.get_brokers(self.region):
            supported_engine_versions = []
            if raw_broker.get('EngineType'):
                supported_engine_versions = await self.facade.mq.get_supported_engine_versions(
                    self.region, raw_broker['EngineType'])

            id, broker = self._parse_broker(raw_broker, supported_engine_versions)
            self[id] = broker

    def _parse_broker(self, raw_broker, supported_engine_versions):
        created = raw_broker.get('Created')

        broker = {}
        # The broker id is generated by Amazon MQ and is what every other API call takes, so it is
        # also what the report and the findings refer to
        broker['id'] = raw_broker['BrokerId']
        broker['name'] = raw_broker.get('BrokerName')
        broker['arn'] = raw_broker.get('BrokerArn')
        broker['region'] = self.region
        broker['engine_type'] = raw_broker.get('EngineType')
        broker['state'] = raw_broker.get('BrokerState')
        broker['creation_time'] = created.strftime('%Y-%m-%d %H:%M:%S') if created else None
        broker['host_instance_type'] = raw_broker.get('HostInstanceType')
        broker['storage_type'] = raw_broker.get('StorageType')
        broker['storage_size'] = raw_broker.get('StorageSize')
        broker['deployment_mode'] = raw_broker.get('DeploymentMode')
        # NONE or CRDR, a cross-Region replication pair whose second broker holds the same messages
        broker['data_replication_mode'] = raw_broker.get('DataReplicationMode')
        # Amazon MQ asks for an intervention through these codes, and a broker carrying one is in the
        # CRITICAL_ACTION_REQUIRED state rather than serving clients normally
        broker['actions_required'] = [action.get('ActionRequiredCode')
                                      for action in raw_broker.get('ActionsRequired') or []]
        broker['tags'] = raw_broker.get('Tags') or {}

        self._parse_network(raw_broker, broker)
        self._parse_version(raw_broker, broker, supported_engine_versions)
        self._parse_encryption(raw_broker, broker)
        self._parse_authentication(raw_broker, broker)
        self._parse_logs(raw_broker, broker)
        self._parse_users(raw_broker, broker)
        self._parse_configuration(raw_broker, broker)

        return broker['id'], broker

    @staticmethod
    def _parse_network(raw_broker, broker):
        # A broker created with public accessibility answers on public addresses, and its security
        # groups become the only boundary between the wire protocols it speaks and the internet
        broker['publicly_accessible'] = bool(raw_broker.get('PubliclyAccessible'))
        broker['subnets'] = raw_broker.get('SubnetIds') or []
        broker['security_groups'] = raw_broker.get('SecurityGroups') or []
        # Security groups changed after creation only take effect on the next reboot, so the ones in
        # force and the ones intended can differ
        broker['pending_security_groups'] = raw_broker.get('PendingSecurityGroups') or []

        instances = raw_broker.get('BrokerInstances') or []
        broker['endpoints'] = [endpoint for instance in instances
                               for endpoint in instance.get('Endpoints') or []]
        # The ActiveMQ web console, or the RabbitMQ management console, of each broker instance
        broker['console_urls'] = [instance['ConsoleURL'] for instance in instances
                                  if instance.get('ConsoleURL')]
        broker['ip_addresses'] = [instance['IpAddress'] for instance in instances
                                  if instance.get('IpAddress')]

    @staticmethod
    def _parse_version(raw_broker, broker, supported_engine_versions):
        version = raw_broker.get('EngineVersion')

        broker['engine_version'] = version
        # Set while an upgrade is waiting for the next reboot or maintenance window
        broker['pending_engine_version'] = raw_broker.get('PendingEngineVersion')
        broker['auto_minor_version_upgrade'] = bool(raw_broker.get('AutoMinorVersionUpgrade'))
        broker['supported_engine_versions'] = supported_engine_versions

        # Amazon MQ retires a version line, not a patch level: it only offers the patch it currently
        # maintains for each line, so a broker sitting on an earlier patch of a line that is still
        # offered is behind on patches, not out of support. Comparing the major and minor keeps that
        # apart from a broker whose whole line Amazon MQ no longer supports.
        if not version or not supported_engine_versions:
            broker['engine_version_supported'] = None
            broker['engine_version_deprecated'] = None
            return

        supported_lines = {_engine_version_line(supported) for supported in supported_engine_versions}
        broker['engine_version_supported'] = _engine_version_line(version) in supported_lines
        broker['engine_version_deprecated'] = not broker['engine_version_supported']

    @staticmethod
    def _parse_encryption(raw_broker, broker):
        """Amazon MQ always encrypts the broker storage, so what is worth reporting is whose key it
        uses. A broker created without encryption options falls back on a key AWS owns, which has no
        policy the account can read, no CloudTrail record of its use and no way to be disabled."""

        encryption = raw_broker.get('EncryptionOptions') or {}

        broker['encryption_kms_key'] = encryption.get('KmsKeyId')
        # UseAwsOwnedKey is required by the API and a key can only be given when it is false, so the
        # flag alone decides whether the account owns the key protecting the messages at rest
        broker['encryption_with_aws_owned_key'] = bool(encryption.get('UseAwsOwnedKey', True))
        broker['encryption_with_cmk'] = not broker['encryption_with_aws_owned_key']

    @staticmethod
    def _parse_authentication(raw_broker, broker):
        """SIMPLE means the broker keeps its own users and passwords, set through the Amazon MQ API.
        LDAP delegates authentication and group membership to a directory, and CONFIG_MANAGED means
        the authentication backends are declared in the broker configuration, which is how a RabbitMQ
        broker is pointed at OAuth 2.0, IAM, LDAP, HTTP or client certificates."""

        strategy = raw_broker.get('AuthenticationStrategy')

        broker['authentication_strategy'] = strategy
        # Applied on the next reboot, so a broker can already be pointed at a directory it does not
        # yet use
        broker['pending_authentication_strategy'] = raw_broker.get('PendingAuthenticationStrategy')
        # SIMPLE is what Amazon MQ applies when the creation request says nothing, so an absent
        # strategy is read as the broker holding its own credentials
        broker['broker_local_credentials'] = strategy in (None, 'SIMPLE')

        ldap = raw_broker.get('LdapServerMetadata') or {}
        broker['ldap_hosts'] = ldap.get('Hosts') or []
        broker['ldap_service_account_username'] = ldap.get('ServiceAccountUsername')
        broker['ldap_user_base'] = ldap.get('UserBase')
        broker['ldap_role_base'] = ldap.get('RoleBase')

    @staticmethod
    def _parse_logs(raw_broker, broker):
        """The two log streams a broker can deliver to CloudWatch Logs. General logging publishes what
        the broker engine itself writes; audit logging records the management actions taken through
        JMX and the ActiveMQ web console, and exists on ActiveMQ brokers only."""

        logs = raw_broker.get('Logs') or {}
        pending = logs.get('Pending') or {}

        broker['general_logs_enabled'] = bool(logs.get('General'))
        broker['general_log_group'] = logs.get('GeneralLogGroup')
        broker['audit_logs_enabled'] = bool(logs.get('Audit'))
        broker['audit_log_group'] = logs.get('AuditLogGroup')
        # Logging turned on but not yet in force, as the change waits for the next reboot
        broker['general_logs_pending'] = pending.get('General')
        broker['audit_logs_pending'] = pending.get('Audit')

    @staticmethod
    def _parse_users(raw_broker, broker):
        """The users of the broker and what each of them may do.

        Only ActiveMQ brokers have users the API describes. A RabbitMQ broker reports the name of the
        administrator it was created with, and its other users, their tags and their permissions live
        inside RabbitMQ where the API cannot see them, so console access is left unknown rather than
        reported as absent."""

        details = {user['Username']: user for user in raw_broker.get('user_details') or []
                   if user.get('Username')}

        users = {}
        for summary in raw_broker.get('Users') or []:
            username = summary.get('Username')
            if not username:
                continue

            detail = details.get(username)
            user_id = get_non_provider_id(username)
            users[user_id] = {
                'id': user_id,
                'name': username,
                'username': username,
                # Set while a change to the user waits for the next reboot
                'pending_change': summary.get('PendingChange'),
                'console_access': detail.get('ConsoleAccess') if detail else None,
                # The ActiveMQ groups the user belongs to, which is what an authorization entry names
                'groups': detail.get('Groups') or [] if detail else [],
                # The user Amazon MQ uses to replicate messages to the other broker of a CRDR pair
                'replication_user': detail.get('ReplicationUser') if detail else None,
            }

        broker['users'] = users
        broker['users_count'] = len(users)
        broker['users_with_console_access'] = sorted(
            user['username'] for user in users.values() if user['console_access'])

    def _parse_configuration(self, raw_broker, broker):
        configurations = raw_broker.get('Configurations') or {}
        current = configurations.get('Current') or {}
        pending = configurations.get('Pending') or {}

        broker['configuration_id'] = current.get('Id')
        broker['configuration_revision'] = current.get('Revision')
        # A revision applied but not yet in force, as it waits for the next reboot
        broker['pending_configuration_revision'] = pending.get('Revision')

        self._parse_authorization_map(raw_broker, broker)

    @staticmethod
    def _parse_authorization_map(raw_broker, broker):
        """Read the authorization map out of the ActiveMQ configuration the broker currently runs.

        ActiveMQ consults no authorization map unless an authorizationPlugin declares one, and each
        entry of that map names the groups allowed to read from, write to and administer a set of
        destinations. RabbitMQ keeps its permissions inside the broker, so nothing is decided for a
        RabbitMQ broker, and neither is anything decided for a broker whose configuration could not
        be read: both are reported as unknown rather than as a broker without a map."""

        broker['authorization_map_configured'] = None
        broker['authorization_entries'] = []

        data = raw_broker.get('configuration_data')
        if broker.get('engine_type') != 'ACTIVEMQ' or not data:
            return

        try:
            # The document is the configuration Amazon MQ validated against its own whitelist of
            # permitted elements, so it is well formed XML with the ActiveMQ core namespace on it
            root = ElementTree.fromstring(data)
        except ElementTree.ParseError as e:
            print_exception(f'Failed to parse the ActiveMQ configuration of broker '
                            f'{broker.get("name")}: {e}')
            return

        entries, plugin_configured = [], False
        for element in root.iter():
            # Every element carries the namespace as a prefix on its tag, and which namespace the
            # configuration declares is not something a rule should depend on
            tag = element.tag.split('}')[-1]
            if tag == 'authorizationPlugin':
                plugin_configured = True
            elif tag == 'authorizationEntry':
                destination_type = next(
                    (candidate for candidate in AUTHORIZATION_DESTINATION_TYPES
                     if element.get(candidate) is not None), None)
                entries.append({
                    'destination': element.get(destination_type) if destination_type else None,
                    'destination_type': destination_type,
                    'read': element.get('read'),
                    'write': element.get('write'),
                    'admin': element.get('admin'),
                })

        broker['authorization_map_configured'] = plugin_configured
        broker['authorization_entries'] = entries


def _engine_version_line(version):
    """The major and minor of an engine version, which is the granularity at which Amazon MQ supports
    or retires one. Patch levels inside a line are what an automatic minor version upgrade moves."""

    return '.'.join(version.split('.')[:2])
